receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:8080
      grpc:


exporters:
  influxdb:
    endpoint: https://eu-central-1-1.aws.cloud2.influxdata.com/
    bucket: quix-otel
    token: ICY-qzrAuYAmPJOR3UmA-6Y3haaUg0nkrd0cR3E1PlobcCG-78er_ddW4M49qoobdChZg6bpVs2hA-nntITRSQ==
    metrics_schema: otel-v1

connectors:
  spanmetrics:
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
  servicegraph:

service:
  telemetry:
    logs:
      level: debug
      encoding: json

  pipelines:
    traces:
      receivers: [otlp]
      exporters: [influxdb, spanmetrics, servicegraph]

    metrics:
      receivers: [spanmetrics, servicegraph]
      exporters: [influxdb]
